// Generated by tools/gen_vlw.py -- DO NOT EDIT BY HAND.
// Faces: HelveticaNeue.ttc, DSEG7Classic-Bold.ttf.
// 4 subsets, 90987 bytes of .vlw.
#pragma once
#include <Arduino.h>

// Anti-aliased Latin, for TFT_eSPI::loadFont(const uint8_t[]).
// Load these through font_use() in uitext.h, never directly:
// only one smooth font can be loaded at a time, and every swap
// reallocates its metrics, so the swap wants deduplicating.
enum UiFont : uint8_t {
  UI_FONT_S,      // 13 px box, 95 glyphs, fontHeight() 16, widest 13 px -- was Font 2
  UI_FONT_M,      // 22 px box, 95 glyphs, fontHeight() 26, widest 22 px -- was Font 4
  UI_FONT_L,      // 66 px ink, 13 glyphs, fontHeight() 48, widest 37 px -- was Font 6
  UI_FONT_XL,     // 71 px ink, 11 glyphs, fontHeight() 71, widest 58 px -- was Font 8
  UI_FONT_COUNT
};

extern const uint8_t* const UI_FONTS[UI_FONT_COUNT];
