// Generated by tools/gen_zh_labels.py -- DO NOT EDIT BY HAND.
// Font: STHeiti Medium.ttc (face 0).
// 93 labels, 14050 bytes of bitmap.
#pragma once
#include <Arduino.h>

enum ZhLabel : uint8_t {
  ZH_FEN_ZHONG,    // 分鐘  18px, 36x17
  ZH_ARRIVING,     // 即將到站  20px, 78x18
  ZH_NO_SERVICE,   // 無服務  24px, 71x23
  ZH_NOT_SET,      // 未設定  24px, 70x23
  ZH_NO_CLOCK,     // 未校時  24px, 70x23
  ZH_NO_DATA,      // 無數據  24px, 70x23
  ZH_CHECK_STOP,   // 檢查車站  20px, 79x18
  ZH_SCHEDULED,    // 未開出  18px, 51x17
  ZH_DEPARTED,     // 已開出  18px, 51x17
  ZH_LAST_BUS,     // 尾班車  18px, 53x17
  ZH_TIMETABLE,    // 原定班次  18px, 71x17
  ZH_TO,           // 往  18px, 18x17
  ZH_STOP_WORD,    // 站  18px, 18x17
  ZH_UPDATED,      // 更新  16px, 32x17
  ZH_SEC_AGO,      // 秒前  16px, 31x17
  ZH_MIN_AGO,      // 分前  16px, 31x17
  ZH_NEXT_BUS,     // 下一班車  20px, 78x18
  ZH_LOADING,      // 載入中  24px, 68x23
  ZH_ADD_STOPS,    // 在設定頁加入巴士站  18px, 161x17
  ZH_YEAR,         // 年  22px, 20x21
  ZH_MONTH,        // 月  22px, 18x21
  ZH_DAY,          // 日  22px, 14x21
  ZH_WEEKDAY,      // 星期  22px, 42x21
  ZH_WD_0,         // 日  22px, 14x21
  ZH_WD_1,         // 一  22px, 20x21
  ZH_WD_2,         // 二  22px, 20x21
  ZH_WD_3,         // 三  22px, 20x21
  ZH_WD_4,         // 四  22px, 18x21
  ZH_WD_5,         // 五  22px, 20x21
  ZH_WD_6,         // 六  22px, 20x21
  ZH_SETUP_AT,     // 設定:  16px, 36x17
  ZH_WIFI_OFFLINE, // WiFi 離線  16px, 65x17
  ZH_SYNCING,      // 校時中…  22px, 85x21
  ZH_WX_CLEAR,     // 晴  18px, 16x17
  ZH_WX_PARTLY,    // 部分多雲  18px, 71x17
  ZH_WX_CLOUD,     // 多雲  18px, 34x17
  ZH_WX_FOG,       // 霧  18px, 16x17
  ZH_WX_RAIN,      // 雨  18px, 16x17
  ZH_WX_SNOW,      // 雪  18px, 16x17
  ZH_WX_THUNDER,   // 雷暴  18px, 35x17
  ZH_WX_LOADING,   // 讀取天氣中…  22px, 129x21
  ZH_FEELS,        // 體感  16px, 32x17
  ZH_CLOUD_PCT,    // 雲量  16px, 31x17
  ZH_HUMIDITY,     // 濕度  16px, 32x17
  ZH_WIND,         // 風速  16px, 32x17
  ZH_AQI_TITLE,    // 空氣質素指數  16px, 95x17
  ZH_AQI_LOADING,  // 讀取空氣質素中…  22px, 173x21
  ZH_AQI_GOOD,     // 良好  22px, 43x21
  ZH_AQI_MODERATE, // 中等  22px, 41x21
  ZH_AQI_SENSITIVE, // 敏感者不宜  22px, 109x21
  ZH_AQI_UNHEALTHY, // 不健康  22px, 64x21
  ZH_AQI_VERY_BAD, // 極不健康  22px, 86x21
  ZH_AQI_HAZARD,   // 危害  22px, 42x21
  ZH_SUNRISE,      // 日出  16px, 27x17
  ZH_SUNSET,       // 日落  16px, 28x17
  ZH_UV,           // 紫外線  16px, 47x17
  ZH_TOMORROW,     // 明天  16px, 31x17
  ZH_GOLDEN_HOUR,  // 黃金時刻  16px, 62x17
  ZH_LIT,          // 亮度  16px, 31x17
  ZH_NOW,          // 現在  22px, 43x21
  ZH_HOURS,        // 小時  22px, 43x21
  ZH_MINUTES,      // 分  22px, 21x21
  ZH_AFTER,        // 後  22px, 22x21
  ZH_MOON_NEW,     // 新月  16px, 30x17
  ZH_MOON_WAX_CRE, // 蛾眉月  16px, 46x17
  ZH_MOON_FIRST_Q, // 上弦月  16px, 46x17
  ZH_MOON_WAX_GIB, // 盈凸月  16px, 45x17
  ZH_MOON_FULL,    // 滿月  16px, 30x17
  ZH_MOON_WAN_GIB, // 虧凸月  16px, 46x17
  ZH_MOON_LAST_Q,  // 下弦月  16px, 45x17
  ZH_MOON_WAN_CRE, // 殘月  16px, 30x17
  ZH_BOOT_STORAGE, // 準備儲存空間…  22px, 151x21
  ZH_BOOT_WIFI,    // 連接WiFi中…  22px, 125x21
  ZH_BOOT_SAVED,   // 已儲存，重新啟動  22px, 173x21
  ZH_SETUP_TITLE,  // 設定  22px, 43x21
  ZH_SETUP_JOIN,   // 1. 加入此 WiFi 網絡  16px, 132x17
  ZH_SETUP_AUTO,   // 2. 設定頁面會自動開啟，  16px, 170x17
  ZH_SETUP_OR,     // 或前往  16px, 48x17
  ZH_CAL_TL,       // 左上  22px, 42x21
  ZH_CAL_TR,       // 右上  22px, 42x21
  ZH_CAL_BR,       // 右下  22px, 42x21
  ZH_CAL_BL,       // 左下  22px, 42x21
  ZH_CAL_HOLD,     // 用力按住  16px, 63x17
  ZH_CAL_CONFIRM,  // 點擊中央確認  16px, 96x17
  ZH_CAL_TITLE,    // 觸控設定  22px, 87x21
  ZH_CAL_PRESS_EACH, // 逐一用力按下目標  16px, 128x17
  ZH_CAL_SKIPPED,  // 略過觸控設定  22px, 130x21
  ZH_CAL_KEEPING,  // 沿用先前校正  16px, 95x17
  ZH_CAL_DONE,     // 觸控校正完成  22px, 132x21
  ZH_CAL_NOT_QUITE, // 未夠準確  22px, 86x21
  ZH_CAL_OFF_BY,   // 像素，請再試  16px, 96x17
  ZH_CAL_ROUGH,    // 已儲存（粗略）  22px, 138x21
  ZH_CAL_REDO,     // 隨時長按4秒重做  16px, 120x17
  ZH_COUNT
};

// Blob layout: [0]=w, [1]=h, then packed 1-bpp rows, MSB first, each
// row padded to a whole byte -- exactly what TFT_eSPI::drawBitmap wants.
extern const uint8_t* const ZH_LABELS[ZH_COUNT];
