// Generated by tools/gen_zh_labels.py -- DO NOT EDIT BY HAND.
// Font: STHeiti Medium.ttc (face 0).
// 18 labels, 2488 bytes of bitmap.
#pragma once
#include <Arduino.h>

enum ZhLabel : uint8_t {
  ZH_FEN_ZHONG,    // 分鐘  18px, 36x17
  ZH_ARRIVING,     // 即將到站  20px, 78x18
  ZH_NO_SERVICE,   // 無服務  24px, 71x23
  ZH_NOT_SET,      // 未設定  24px, 70x23
  ZH_NO_CLOCK,     // 未校時  24px, 70x23
  ZH_NO_DATA,      // 無數據  24px, 70x23
  ZH_CHECK_STOP,   // 檢查車站  20px, 79x18
  ZH_SCHEDULED,    // 未開出  18px, 51x17
  ZH_DEPARTED,     // 已開出  18px, 51x17
  ZH_LAST_BUS,     // 尾班車  18px, 53x17
  ZH_TIMETABLE,    // 原定班次  18px, 71x17
  ZH_TO,           // 往  18px, 18x17
  ZH_STOP_WORD,    // 站  18px, 18x17
  ZH_UPDATED,      // 更新  16px, 32x15
  ZH_SEC_AGO,      // 秒前  16px, 31x15
  ZH_MIN_AGO,      // 分前  16px, 31x15
  ZH_NEXT_BUS,     // 下一班車  20px, 78x18
  ZH_LOADING,      // 載入中  24px, 68x23
  ZH_COUNT
};

// Blob layout: [0]=w, [1]=h, then packed 1-bpp rows, MSB first, each
// row padded to a whole byte -- exactly what TFT_eSPI::drawBitmap wants.
extern const uint8_t* const ZH_LABELS[ZH_COUNT];
