#!/usr/bin/env python3
# ---------------------------------------------------------------------------
# preview_labels.py -- render the baked Chinese vocabulary as a contact sheet
# ---------------------------------------------------------------------------
# labels.h says the Chinese is the one part of this feature that cannot be
# verified by assertion, and that the only instrument is a pair of eyes. On the
# device that means label_selfTest and a flash cycle. This is the host-side
# version: it reads the GENERATED bytes back -- not the source strings, not the
# TTF -- and paints them at the size they will ship at, beside the identifier
# the firmware knows them by.
#
# Reading the generated array rather than re-rendering the text is the whole
# point: it catches a label that packed wrong, cropped short, or landed in the
# table under someone else's name.
#
#   python3 tools/preview_labels.py out.png
# ---------------------------------------------------------------------------

import os
import re
import sys

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    sys.exit("Pillow is required:  python3 -m pip install Pillow")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CPP = os.path.join(ROOT, "app", "zh_labels.cpp")
HDR = os.path.join(ROOT, "app", "zh_labels.h")

CAPTION = [
    "/System/Library/Fonts/Menlo.ttc",
    "/System/Library/Fonts/Courier.ttc",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
]


def blobs():
    """(identifier, bytes) for every label, in enum order."""
    src = open(CPP, encoding="utf-8").read()
    found = {}
    for m in re.finditer(r"static const uint8_t ZH_(\w+)_BITS\[\] PROGMEM = \{(.*?)\};",
                         src, re.S):
        found[m.group(1)] = bytes(
            int(b, 16) for b in re.findall(r"0x([0-9A-Fa-f]{2})", m.group(2)))
    # Enum order, so the sheet reads in the same order as zh_labels.h.
    order = re.findall(r"^\s*ZH_(\w+),", open(HDR, encoding="utf-8").read(), re.M)
    return [(i, found[i]) for i in order if i in found]


def unpack(blob):
    """1-bpp back to an 8-bit image -- the same bits drawBitmap reads."""
    w, h = blob[0], blob[1]
    row_bytes = (w + 7) // 8
    img = Image.new("L", (w, h), 0)
    px = img.load()
    for y in range(h):
        for x in range(w):
            b = blob[2 + y * row_bytes + (x >> 3)]
            px[x, y] = 255 if (b & (0x80 >> (x & 7))) else 0
    return img


def caption_font(size):
    for p in CAPTION:
        if os.path.exists(p):
            try:
                return ImageFont.truetype(p, size)
            except OSError:
                pass
    return ImageFont.load_default()


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "zh_labels.png"
    items = blobs()
    if not items:
        sys.exit(f"no labels found in {CPP}")

    pad, gutter, name_w = 8, 6, 190
    rows = [(i, unpack(b)) for i, b in items]
    height = sum(max(im.height, 16) + gutter for _, im in rows) + 2 * pad
    width = name_w + max(im.width for _, im in rows) + 3 * pad

    sheet = Image.new("RGB", (width, height), (0, 0, 0))
    draw = ImageDraw.Draw(sheet)
    font = caption_font(11)

    y = pad
    for ident, im in rows:
        band = max(im.height, 16)
        draw.text((pad, y + band // 2 - 6), f"ZH_{ident}", font=font, fill=(110, 200, 255))
        # Paste as white ink through the alpha, exactly as blit() ramps it
        # between fg and bg on a black background.
        sheet.paste(Image.new("RGB", im.size, (255, 255, 255)),
                    (name_w + pad, y + (band - im.height) // 2), im)
        draw.text((width - pad - 46, y + band // 2 - 6),
                  f"{im.width}x{im.height}", font=font, fill=(90, 90, 90))
        y += band + gutter

    sheet.save(out)
    total = sum(len(b) for _, b in items)
    print(f"{out}: {len(items)} labels, {total} B of bitmap")


if __name__ == "__main__":
    main()
